### ISSUE TITLE
Failed to install 'cordova-plugin-paytm': CordovaError: Uh oh!

### ISSUE THREAD

**Issue by RavikumarRapolu** [ArunYogi/paytm-cordova-plugin#19]
If am trying to install cordova plugin getting Failed to install 'cordova-plugin-paytm': CordovaError: Uh oh! exxeption.

"F:\ionic\testApp\plugins\cordova-plugin-paytm\app\src\android\res\values\paytmcordova.xml" not found!
    at copyFile (F:\ionic\testApp\platforms\android\cordova\lib\pluginHandlers.js:233:36)
    at copyNewFile (F:\ionic\testApp\platforms\android\cordova\lib\pluginHandlers.js:261:5)
    at install (F:\ionic\testApp\platforms\android\cordova\lib\pluginHandlers.js:43:17)
    at ActionStack.process (F:\ionic\testApp\platforms\android\cordova\node_modules\cordova-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (F:\ionic\testApp\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:114:20)
    at PluginManager.addPlugin (F:\ionic\testApp\platforms\android\cordova\node_modules\cordova-common\src\PluginManager.js:144:17)
    at F:\ionic\testApp\platforms\android\cordova\Api.js:247:74
    at _fulfilled (F:\ionic\testApp\platforms\android\cordova\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (F:\ionic\testApp\platforms\android\cordova\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (F:\ionic\testApp\platforms\android\cordova\node_modules\q\

**Comment by ArunYogi** [comment]
Issue is the file reference in latest release. corrected in 0.0.10
